apiVersion: v1
kind: PersistentVolume
metadata:
  name: nexus-local-pv
  labels:
    type: local  
    app: nexus
    tier: platform
spec:
  capacity:
    storage: {{cookiecutter.nexus_volume_size}}
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: /tmp/pv-nexus
---
