apiVersion: v1
kind: PersistentVolume
metadata:
  name: rmqadmin-local-pv
  labels:
    type: local  
    app: rabbitmq
    tier: platform
spec:
  capacity:
    storage: 10G
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: /tmp/pv-rabbitmq
---
