apiVersion: v1
kind: PersistentVolume
metadata:
  name: rcktchat-local-pv
  labels:
    type: local  
    app: rocketchat
    tier: devops
    volumelabel: data
spec:
  capacity:
    storage: {{cookiecutter.rocketchat_container_size}}
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: /tmp/pv-rabbitmq
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: rcktchat-dump-local-pv
  labels:
    type: local
    app: rocketchat
    tier: devops        
    volumelabel: dump
spec:
  capacity:
    storage: {{cookiecutter.rocketchat_container_size}}
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: /tmp/pv-rabbitmq
---
---    