apiVersion: v1
kind: Service
metadata:
  name: letsencrypt
  labels:
    app: letsencrypt
    tier: platform
spec:
  ports:
    - port: 80
      name: http
  selector:
    app: letsencrypt
    tier: platform
  clusterIP: None
  