apiVersion: v1
kind: Service
metadata:
  name: teamcity-server
  labels:
    app: teamcity-server
    tier: devops
spec:
  ports:
    - port: 8111
      name: tc-server-http
  selector:
    app: teamcity-server
    tier: devops
  clusterIP: None