apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: teamcity-agent-pv-claim
  labels:
    app: teamcity-agent
    tier: platform
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  selector:
      matchLabels:
        app: teamcity-agent
        tier: platform

