apiVersion: v1
kind: Service
metadata:
  name: teamcity-agent
  labels:
    app: teamcity-agent
    tier: platform
spec:
  ports:
    - port: tc-agenthttp
  selector:
    app: teamcity-agent
    tier: platform
  clusterIP: None