apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rabbitmq-pv-claim
  labels:
    app: rabbitmq
    tier: platform
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10G
  selector:
      matchLabels:
        app: rabbitmq
        tier: platform

