# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: local-pv-rabbitmq
#   labels:
#     type: local
# spec:
#   capacity:
#     storage: 5Gi
#   accessModes:
#     - ReadWriteOnce
#   persistentVolumeReclaimPolicy: Recycle
#   hostPath:
#     path: /tmp/pv-rabbitmq
# ---

  apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: rabbitmq-pv-claim
    labels:
      app: rabbitmq
      tier: platform
  spec:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 5Gi
---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq
    tier: platform
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: rabbitmq
        tier: platform
    spec:
      containers:
      - image: rabbitmq:3-management
        name: rabbitmq
        imagePullPolicy: IfNotPresent      
        ports:
          - containerPort: 15672
            name: rabbitmq-admin
        volumeMounts:
          - name: rabbitmq-persistent-storage
            mountPath: /var/lib/rabbitmq/          
      volumes:
          - name: rabbitmq-persistent-storage
            persistentVolumeClaim:
                claimName: rabbitmq-pv-claim
---

apiVersion: v1
kind: Service
metadata:
  name: feeds-rabbitmq
  labels:
    app: rabbitmq
    tier: platform
spec:
  ports:
    - port: 15672
      name: rabbitmq-admin
  selector:
    app: rabbitmq
    tier: platform
  clusterIP: None
---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name:  rabbitmq-ingress
  annotations:
    ingress.kubernetes.io/rewrite-target: /
    #ingress.kubernetes.io/add-base-url: "true"
    # ingress.kubernetes.io/ssl-redirect: "false"

spec:
  rules:
  - host: rabbitmq.atlas.cloud
    http:
      paths:
      - path: /
        backend:
          serviceName: feeds-rabbitmq
          servicePort: 15672        

          # serviceName: foswiki-svc
          # servicePort: 80

      # - path: /
      #   backend:
      #     serviceName: feeds-rabbitmq
      #     servicePort: 15672

---
