apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq
    tier: platform
spec:
  ports:
    - port: rmqadmin
  selector:
    app: rabbitmq
    tier: platform
  clusterIP: None