apiVersion: v1
kind: Service
metadata:
  name: devops-rockchat
  labels:
    app: rocketchat
    tier: devops
spec:
  ports:
    - port: 3000
      name: rchat-http
    - port: 3001
      name: rchat-https      
  selector:
    app: rocketchat
    tier: devops
  clusterIP: None