apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name:  nexus-ingress
spec:
  rules:
  - host: nexus.{{cookiecutter.stratus_root_domain}}
    http:
      paths:
      - path: /
        backend:
          serviceName: platform-nexus
          servicePort: nexus
