apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nexus-pv-claim
  labels:
    app: nexus
    tier: platform
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{cookiecutter.nexus_volume_size}}
  selector:
    matchLabels:
      type: local  
      app: nexus
      tier: platform
