apiVersion: v1
kind: Service
metadata:
  name: platform-nexus
  labels:
    app: nexus
    tier: platform
spec:
  ports:
    - port: 8081
      name: nexus
  selector:
    app: nexus
    tier: platform
  clusterIP: None